spring: 
  datasource: 
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}

    
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
server:
  port: 8087
